name:                amf
version:             0.0.1
github:              "adamflott/amf"
license:             BSD3
author:              "Adam Flott"
maintainer:          "adam@adamflott..com"
copyright:           "2020 Adam Flott"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/adamflott/amf#readme>

ghc-options:
  - -Wall
  - -O
  - -fwarn-unused-imports
  - -fhide-source-paths
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Wpartial-fields
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wmissing-deriving-strategies
#  - -Wmissing-export-lists
#  - -Werror
#  - -Wunused-packages

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTSyntax
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoMonomorphismRestriction
  - NoImplicitPrelude
  - NumDecimals
  - NumericUnderscores
  - OverloadedStrings
  - ParallelListComp
  - PatternGuards
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StaticPointers
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
  - UnicodeSyntax
  - ViewPatterns
  - UndecidableInstances

dependencies:
- base >= 4.14 && < 5.0
- HsYAML
- SHA
- Glob
- aeson
- async
- broadcast-chan
- bytestring
- cassava
- chronos
- clock
- containers
- data-has
- directory
- dlist
- docker
- dockerfile-creator
- envy
- exceptions
- filepath
- fsnotify
- hedgehog
- hostname
- hxt
- ip
- kubernetes-client
- kubernetes-client-core
- language-docker
- lens
- lifted-async
- megaparsec
- monad-control
- mtl
- network
- optparse-applicative >= 0.16.0.0
- ordered-containers
- path >= 0.8.0
- path-io
- pretty-simple
- prettyprinter
- relude >= 0.7.0.0
- resourcet
- retry
- safe-exceptions
- serialise
- split
- statgrab
- stm
- temporary
- text
- time
- tls
- tomland
- transformers
- transformers-base
- turtle >= 1.5.21 && <= 1.6.0
- typed-process
- unagi-chan
- unix
- unliftio
- unordered-containers
- vty
- with-utf8

library:
  source-dirs: src

executables:
  amf-daemon:
    main:                Main.hs
    source-dirs:         examples/daemon
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amf

  amf-script:
    main:                Main.hs
    source-dirs:         examples/script
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amf

tests:
  amf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - amf
